// <auto-generated />
using CarListingApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarListingApp.API.Migrations
{
    [DbContext(typeof(CarListDBContext))]
    [Migration("20231003121402_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("CarListingApp.API.Data.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "Make 1",
                            Model = "Model 1",
                            Vin = "5BC2BB04-6130-4063-8466-5698E6995DBC"
                        },
                        new
                        {
                            Id = 2,
                            Make = "Make 2",
                            Model = "Model 2",
                            Vin = "3442AEC3-08E5-4FFD-A0F3-FE6E9B82C295"
                        },
                        new
                        {
                            Id = 3,
                            Make = "Make 3",
                            Model = "Model 3",
                            Vin = "BF8597C3-8C37-4D15-BDC3-F41C85142639"
                        },
                        new
                        {
                            Id = 4,
                            Make = "Make 4",
                            Model = "Model 4",
                            Vin = "0A65BD4E-3D5E-4684-8984-A0165765ED80"
                        },
                        new
                        {
                            Id = 5,
                            Make = "Make 5",
                            Model = "Model 5",
                            Vin = "7EF403C9-D8D8-43BB-8A2A-2D8E4BA4DE6A"
                        },
                        new
                        {
                            Id = 6,
                            Make = "Make 6",
                            Model = "Model 6",
                            Vin = "550B45E1-FC23-491B-A77F-66AB6EA12D5C"
                        },
                        new
                        {
                            Id = 7,
                            Make = "Make 7",
                            Model = "Model 7",
                            Vin = "422FB740-784C-4C55-9E90-553221F16EC7"
                        },
                        new
                        {
                            Id = 8,
                            Make = "Make 8",
                            Model = "Model 8",
                            Vin = "EE599366-EE04-49A1-B876-70328153F6EC"
                        },
                        new
                        {
                            Id = 9,
                            Make = "Make 9",
                            Model = "Model 9",
                            Vin = "CB4FC223-4BE3-46D1-844F-9A1FE11484BA"
                        },
                        new
                        {
                            Id = 10,
                            Make = "Make 10",
                            Model = "Model 10",
                            Vin = "4A154645-4D68-45FC-B946-12890E8876DB"
                        },
                        new
                        {
                            Id = 11,
                            Make = "Make 11",
                            Model = "Model 11",
                            Vin = "1F6F8926-47D2-4809-A85C-C12E34FA7006"
                        },
                        new
                        {
                            Id = 12,
                            Make = "Make 12",
                            Model = "Model 12",
                            Vin = "8088E108-6B10-48D6-81CE-9F0A1D89DFAD"
                        },
                        new
                        {
                            Id = 13,
                            Make = "Make 13",
                            Model = "Model 13",
                            Vin = "C5EC9C5E-7DA5-438E-9571-5E66548999D2"
                        },
                        new
                        {
                            Id = 14,
                            Make = "Make 14",
                            Model = "Model 14",
                            Vin = "112B44A3-73BF-43D1-92D4-A96D937B9000"
                        },
                        new
                        {
                            Id = 15,
                            Make = "Make 15",
                            Model = "Model 15",
                            Vin = "6E4914D1-1E3D-40F6-ACDA-CE68362E7BF5"
                        },
                        new
                        {
                            Id = 16,
                            Make = "Make 16",
                            Model = "Model 16",
                            Vin = "8BE56BA0-E3F3-4CC6-A7F3-B02F1997BFCF"
                        },
                        new
                        {
                            Id = 17,
                            Make = "Make 17",
                            Model = "Model 17",
                            Vin = "7912244B-E5A7-4CFC-AECB-B0CF2A598C88"
                        },
                        new
                        {
                            Id = 18,
                            Make = "Make 18",
                            Model = "Model 18",
                            Vin = "46341A96-A278-41E4-BD2B-7837E2BB62FF"
                        },
                        new
                        {
                            Id = 19,
                            Make = "Make 19",
                            Model = "Model 19",
                            Vin = "3D1BD3E1-7619-4884-B181-7B8C4FACF025"
                        },
                        new
                        {
                            Id = 20,
                            Make = "Make 20",
                            Model = "Model 20",
                            Vin = "119B4AB7-9EA5-4DFC-BFFB-971430467D0B"
                        },
                        new
                        {
                            Id = 21,
                            Make = "Make 21",
                            Model = "Model 21",
                            Vin = "2A02002E-96DE-4C11-9B69-C0AA8187FB37"
                        },
                        new
                        {
                            Id = 22,
                            Make = "Make 22",
                            Model = "Model 22",
                            Vin = "C2C09EF9-1280-4573-A026-5056F123FF89"
                        },
                        new
                        {
                            Id = 23,
                            Make = "Make 23",
                            Model = "Model 23",
                            Vin = "60D83FBE-7712-423C-B99E-1A7B253970F5"
                        },
                        new
                        {
                            Id = 24,
                            Make = "Make 24",
                            Model = "Model 24",
                            Vin = "0B732C49-8FE8-42A6-BCAF-33659EF7FD61"
                        },
                        new
                        {
                            Id = 25,
                            Make = "Make 25",
                            Model = "Model 25",
                            Vin = "02B1E16D-2A5A-4F48-8820-6CEEDF86F99D"
                        },
                        new
                        {
                            Id = 26,
                            Make = "Make 26",
                            Model = "Model 26",
                            Vin = "F3777647-D6CE-40CE-90D3-21189B61AB0A"
                        },
                        new
                        {
                            Id = 27,
                            Make = "Make 27",
                            Model = "Model 27",
                            Vin = "F625ABDD-12A5-4E5C-BB1F-91AD84B5DD63"
                        },
                        new
                        {
                            Id = 28,
                            Make = "Make 28",
                            Model = "Model 28",
                            Vin = "92C7B501-CE39-4ADD-A337-B2E7DD542F5D"
                        },
                        new
                        {
                            Id = 29,
                            Make = "Make 29",
                            Model = "Model 29",
                            Vin = "A4751A7B-C9D6-4957-A7CD-B42B97F04FCA"
                        },
                        new
                        {
                            Id = 30,
                            Make = "Make 30",
                            Model = "Model 30",
                            Vin = "5C4E9E4C-B56C-4E02-9613-FBEFC89B0E5B"
                        },
                        new
                        {
                            Id = 31,
                            Make = "Make 31",
                            Model = "Model 31",
                            Vin = "B98523E8-BE1C-45F0-A882-AB62374C49E0"
                        },
                        new
                        {
                            Id = 32,
                            Make = "Make 32",
                            Model = "Model 32",
                            Vin = "72FACFF4-F4A4-43C1-B28C-0E6A71070A87"
                        },
                        new
                        {
                            Id = 33,
                            Make = "Make 33",
                            Model = "Model 33",
                            Vin = "7BAC7A78-CCBA-48C9-B2F3-DF33EAF1F624"
                        },
                        new
                        {
                            Id = 34,
                            Make = "Make 34",
                            Model = "Model 34",
                            Vin = "BEC48681-865A-4B0B-8426-6E685678C726"
                        },
                        new
                        {
                            Id = 35,
                            Make = "Make 35",
                            Model = "Model 35",
                            Vin = "C60387AF-6263-4CB4-AC52-61A446111319"
                        },
                        new
                        {
                            Id = 36,
                            Make = "Make 36",
                            Model = "Model 36",
                            Vin = "6E602BBC-9484-4FC9-A109-071EDB6B505D"
                        },
                        new
                        {
                            Id = 37,
                            Make = "Make 37",
                            Model = "Model 37",
                            Vin = "1937651F-4F06-4A02-8359-D70EB1D7B918"
                        },
                        new
                        {
                            Id = 38,
                            Make = "Make 38",
                            Model = "Model 38",
                            Vin = "D291A402-975D-478E-A969-6FD3C7DE5D46"
                        },
                        new
                        {
                            Id = 39,
                            Make = "Make 39",
                            Model = "Model 39",
                            Vin = "B3205CA7-58D9-46AA-B0E7-7B93632B0415"
                        },
                        new
                        {
                            Id = 40,
                            Make = "Make 40",
                            Model = "Model 40",
                            Vin = "17AE704B-96E9-4D23-B85E-E0F7A0A9B441"
                        },
                        new
                        {
                            Id = 41,
                            Make = "Make 41",
                            Model = "Model 41",
                            Vin = "650C814F-822A-4FE9-B7C6-316AB70E4538"
                        },
                        new
                        {
                            Id = 42,
                            Make = "Make 42",
                            Model = "Model 42",
                            Vin = "9818539F-8C03-4004-9516-5C455E8ADAF2"
                        },
                        new
                        {
                            Id = 43,
                            Make = "Make 43",
                            Model = "Model 43",
                            Vin = "8A2C8948-F87E-493F-84F8-0094DFA484CD"
                        },
                        new
                        {
                            Id = 44,
                            Make = "Make 44",
                            Model = "Model 44",
                            Vin = "179612A1-B286-4629-8610-6ACC2CE31A3F"
                        },
                        new
                        {
                            Id = 45,
                            Make = "Make 45",
                            Model = "Model 45",
                            Vin = "69EF8B43-EA47-4C5A-BE43-43E21D8765BA"
                        },
                        new
                        {
                            Id = 46,
                            Make = "Make 46",
                            Model = "Model 46",
                            Vin = "DEA90426-07D8-4EEC-851D-BF6730C07728"
                        },
                        new
                        {
                            Id = 47,
                            Make = "Make 47",
                            Model = "Model 47",
                            Vin = "1E952196-89CE-48BC-A29C-79F59B494AB4"
                        },
                        new
                        {
                            Id = 48,
                            Make = "Make 48",
                            Model = "Model 48",
                            Vin = "D50D5CC9-0F7C-4FC4-89D2-0F8CB8D5ED1B"
                        },
                        new
                        {
                            Id = 49,
                            Make = "Make 49",
                            Model = "Model 49",
                            Vin = "712BBDA6-628A-4C91-B560-AA55B408B018"
                        },
                        new
                        {
                            Id = 50,
                            Make = "Make 50",
                            Model = "Model 50",
                            Vin = "5AD3AA2F-F9DF-4CC3-8F91-88598B11A6C1"
                        },
                        new
                        {
                            Id = 51,
                            Make = "Make 51",
                            Model = "Model 51",
                            Vin = "EB15119A-E2C1-464A-B159-B10C51D5E3C7"
                        },
                        new
                        {
                            Id = 52,
                            Make = "Make 52",
                            Model = "Model 52",
                            Vin = "0CBF30F1-5910-491F-8DF5-FEA6FEE2C6F1"
                        },
                        new
                        {
                            Id = 53,
                            Make = "Make 53",
                            Model = "Model 53",
                            Vin = "79BC21C0-7850-41CB-A26A-1834660392FE"
                        },
                        new
                        {
                            Id = 54,
                            Make = "Make 54",
                            Model = "Model 54",
                            Vin = "B19FB9EF-E491-413E-897C-60263F5253F8"
                        },
                        new
                        {
                            Id = 55,
                            Make = "Make 55",
                            Model = "Model 55",
                            Vin = "900F12BE-6374-482F-8E77-3200B2EBF263"
                        },
                        new
                        {
                            Id = 56,
                            Make = "Make 56",
                            Model = "Model 56",
                            Vin = "6D9EABCF-118B-44D5-B2ED-60754EBE30C6"
                        },
                        new
                        {
                            Id = 57,
                            Make = "Make 57",
                            Model = "Model 57",
                            Vin = "42380B4C-FAC4-4808-AFCF-BD7511059AC5"
                        },
                        new
                        {
                            Id = 58,
                            Make = "Make 58",
                            Model = "Model 58",
                            Vin = "E81708A1-F97D-42B9-A150-60445BA40DD2"
                        },
                        new
                        {
                            Id = 59,
                            Make = "Make 59",
                            Model = "Model 59",
                            Vin = "A4107172-32CD-4E5C-BAD4-324182EDDE2A"
                        },
                        new
                        {
                            Id = 60,
                            Make = "Make 60",
                            Model = "Model 60",
                            Vin = "0137EC99-EF7D-4E79-AD54-991B5DF42E6D"
                        },
                        new
                        {
                            Id = 61,
                            Make = "Make 61",
                            Model = "Model 61",
                            Vin = "64BE24A9-EAB8-4C60-8398-0785400C4287"
                        },
                        new
                        {
                            Id = 62,
                            Make = "Make 62",
                            Model = "Model 62",
                            Vin = "ABBDAC23-9F7F-4445-87D1-F2CD59C3AF73"
                        },
                        new
                        {
                            Id = 63,
                            Make = "Make 63",
                            Model = "Model 63",
                            Vin = "F4CB0830-9242-4419-854B-ED60C27D1AD3"
                        },
                        new
                        {
                            Id = 64,
                            Make = "Make 64",
                            Model = "Model 64",
                            Vin = "B7440982-2F9D-475E-BFC8-4A463248895F"
                        },
                        new
                        {
                            Id = 65,
                            Make = "Make 65",
                            Model = "Model 65",
                            Vin = "24E61148-34DF-41A0-A141-5E297B2DC432"
                        },
                        new
                        {
                            Id = 66,
                            Make = "Make 66",
                            Model = "Model 66",
                            Vin = "934037F9-15FD-47C2-AA70-204729A7BBB3"
                        },
                        new
                        {
                            Id = 67,
                            Make = "Make 67",
                            Model = "Model 67",
                            Vin = "F26CA966-BE8D-4417-BCD2-ED192FF295E1"
                        },
                        new
                        {
                            Id = 68,
                            Make = "Make 68",
                            Model = "Model 68",
                            Vin = "6FDBD1D8-1CDA-4A8F-A99F-6466A08AD276"
                        },
                        new
                        {
                            Id = 69,
                            Make = "Make 69",
                            Model = "Model 69",
                            Vin = "0CD9DF06-DB7E-4FFA-A874-4FF220C4E2C0"
                        },
                        new
                        {
                            Id = 70,
                            Make = "Make 70",
                            Model = "Model 70",
                            Vin = "17F6C7C2-A1B1-46E8-B0CA-4322191F02BF"
                        },
                        new
                        {
                            Id = 71,
                            Make = "Make 71",
                            Model = "Model 71",
                            Vin = "CAEA0437-2F69-4095-B89A-29DF82C4095A"
                        },
                        new
                        {
                            Id = 72,
                            Make = "Make 72",
                            Model = "Model 72",
                            Vin = "F7886A8F-2CCB-4CAA-910A-4F754E522F77"
                        },
                        new
                        {
                            Id = 73,
                            Make = "Make 73",
                            Model = "Model 73",
                            Vin = "6F9313CF-E274-4621-A294-21FDAE78F2AF"
                        },
                        new
                        {
                            Id = 74,
                            Make = "Make 74",
                            Model = "Model 74",
                            Vin = "40BA7B2B-2F34-49E8-A6EF-043B8C4FA9F7"
                        },
                        new
                        {
                            Id = 75,
                            Make = "Make 75",
                            Model = "Model 75",
                            Vin = "68DA8B20-4AA8-48CA-A60A-0DF7CC97ACCF"
                        },
                        new
                        {
                            Id = 76,
                            Make = "Make 76",
                            Model = "Model 76",
                            Vin = "C74D8741-1C08-498F-B277-7FB239C1A412"
                        },
                        new
                        {
                            Id = 77,
                            Make = "Make 77",
                            Model = "Model 77",
                            Vin = "6923792F-F129-43BD-8322-64659D73D98E"
                        },
                        new
                        {
                            Id = 78,
                            Make = "Make 78",
                            Model = "Model 78",
                            Vin = "3546B542-B947-4529-A9B1-A72CE8AA2733"
                        },
                        new
                        {
                            Id = 79,
                            Make = "Make 79",
                            Model = "Model 79",
                            Vin = "B27A1244-3B27-4C64-9E9B-233CAEA8FD51"
                        },
                        new
                        {
                            Id = 80,
                            Make = "Make 80",
                            Model = "Model 80",
                            Vin = "E21D8325-5079-4702-B341-46E5E2C062D9"
                        },
                        new
                        {
                            Id = 81,
                            Make = "Make 81",
                            Model = "Model 81",
                            Vin = "98DA9CA0-684E-4B3D-A623-0CA145824C78"
                        },
                        new
                        {
                            Id = 82,
                            Make = "Make 82",
                            Model = "Model 82",
                            Vin = "BE42535A-8333-4C1B-BF18-5DF245B12777"
                        },
                        new
                        {
                            Id = 83,
                            Make = "Make 83",
                            Model = "Model 83",
                            Vin = "D7D918C1-A729-4CB0-829C-C3C1CEE367A2"
                        },
                        new
                        {
                            Id = 84,
                            Make = "Make 84",
                            Model = "Model 84",
                            Vin = "52302A28-889E-4603-9DCD-BCABC2C5B53F"
                        },
                        new
                        {
                            Id = 85,
                            Make = "Make 85",
                            Model = "Model 85",
                            Vin = "7BC93997-91B0-442A-8292-E8D5778A63D7"
                        },
                        new
                        {
                            Id = 86,
                            Make = "Make 86",
                            Model = "Model 86",
                            Vin = "727B2E39-7C24-44A0-956C-B583A0C88076"
                        },
                        new
                        {
                            Id = 87,
                            Make = "Make 87",
                            Model = "Model 87",
                            Vin = "F1B9AF3E-F011-41CD-9467-321E7713CC2C"
                        },
                        new
                        {
                            Id = 88,
                            Make = "Make 88",
                            Model = "Model 88",
                            Vin = "D6846ED3-CE6C-4D2E-B605-24AFA110C737"
                        },
                        new
                        {
                            Id = 89,
                            Make = "Make 89",
                            Model = "Model 89",
                            Vin = "FA4CAED1-27C5-4B54-8015-E70E34C8CA4A"
                        },
                        new
                        {
                            Id = 90,
                            Make = "Make 90",
                            Model = "Model 90",
                            Vin = "BBEB6EE0-155F-4713-A3C4-3B0416763800"
                        },
                        new
                        {
                            Id = 91,
                            Make = "Make 91",
                            Model = "Model 91",
                            Vin = "1757DC1E-AA8D-4D35-97DA-6CA2A8D60FDF"
                        },
                        new
                        {
                            Id = 92,
                            Make = "Make 92",
                            Model = "Model 92",
                            Vin = "A0D5BC73-F443-4514-AA8A-346A0E2EA551"
                        },
                        new
                        {
                            Id = 93,
                            Make = "Make 93",
                            Model = "Model 93",
                            Vin = "FE52C1DF-7CAE-411D-8230-61D2255CF194"
                        },
                        new
                        {
                            Id = 94,
                            Make = "Make 94",
                            Model = "Model 94",
                            Vin = "43377088-3E0F-4E5B-B7C6-9818DA001977"
                        },
                        new
                        {
                            Id = 95,
                            Make = "Make 95",
                            Model = "Model 95",
                            Vin = "5AE2E400-0763-45A9-98C0-C2057D71B683"
                        },
                        new
                        {
                            Id = 96,
                            Make = "Make 96",
                            Model = "Model 96",
                            Vin = "3F5CBF32-55B6-46E4-90F6-FFA9CBC25E59"
                        },
                        new
                        {
                            Id = 97,
                            Make = "Make 97",
                            Model = "Model 97",
                            Vin = "81BD5C6F-7571-4E50-9C3E-01EDFF799368"
                        },
                        new
                        {
                            Id = 98,
                            Make = "Make 98",
                            Model = "Model 98",
                            Vin = "88C305D0-2FED-4DF4-B39A-3A03E8B195C9"
                        },
                        new
                        {
                            Id = 99,
                            Make = "Make 99",
                            Model = "Model 99",
                            Vin = "0C751606-522F-461A-9CC6-FFB029D694E8"
                        },
                        new
                        {
                            Id = 100,
                            Make = "Make 100",
                            Model = "Model 100",
                            Vin = "51CEE71D-1AA7-465C-A004-4047AA01FBE3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
