// <auto-generated />
using System;
using CarListingApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarListingApp.API.Migrations
{
    [DbContext(typeof(CarListDBContext))]
    [Migration("20231017140526_addedidentitytables")]
    partial class addedidentitytables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("CarListingApp.API.Data.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "Make 1",
                            Model = "Model 1",
                            Vin = "9EE1991B-AD9D-4CA0-9D38-B1B55210D019"
                        },
                        new
                        {
                            Id = 2,
                            Make = "Make 2",
                            Model = "Model 2",
                            Vin = "D906F5E3-526E-462E-9329-2AB8B3DFBC18"
                        },
                        new
                        {
                            Id = 3,
                            Make = "Make 3",
                            Model = "Model 3",
                            Vin = "8971FD6A-5D46-46FD-9941-457CDD86C7B5"
                        },
                        new
                        {
                            Id = 4,
                            Make = "Make 4",
                            Model = "Model 4",
                            Vin = "F1884753-2EA4-48DE-89D9-7EE24AD6277D"
                        },
                        new
                        {
                            Id = 5,
                            Make = "Make 5",
                            Model = "Model 5",
                            Vin = "ED5AB316-2950-4EC2-B7DD-9212D9476CC8"
                        },
                        new
                        {
                            Id = 6,
                            Make = "Make 6",
                            Model = "Model 6",
                            Vin = "8DE4A7C1-0FEE-49A9-847E-CC693849E0E8"
                        },
                        new
                        {
                            Id = 7,
                            Make = "Make 7",
                            Model = "Model 7",
                            Vin = "F602684D-480F-4A75-9A3D-E1B276F4300F"
                        },
                        new
                        {
                            Id = 8,
                            Make = "Make 8",
                            Model = "Model 8",
                            Vin = "26F01C3A-5033-4277-9560-120E28AD730E"
                        },
                        new
                        {
                            Id = 9,
                            Make = "Make 9",
                            Model = "Model 9",
                            Vin = "E6E74FAB-F4DC-4B75-A6DA-996FA3702C64"
                        },
                        new
                        {
                            Id = 10,
                            Make = "Make 10",
                            Model = "Model 10",
                            Vin = "9BD889B8-520E-464D-A1E0-814981736B83"
                        },
                        new
                        {
                            Id = 11,
                            Make = "Make 11",
                            Model = "Model 11",
                            Vin = "D382ACEF-41E5-4D7F-B998-7037D3409C6E"
                        },
                        new
                        {
                            Id = 12,
                            Make = "Make 12",
                            Model = "Model 12",
                            Vin = "B8C54F4C-8722-4E8F-BC8C-D383BA5A3400"
                        },
                        new
                        {
                            Id = 13,
                            Make = "Make 13",
                            Model = "Model 13",
                            Vin = "14925ED2-0B9E-4854-875D-9E2F30B1425B"
                        },
                        new
                        {
                            Id = 14,
                            Make = "Make 14",
                            Model = "Model 14",
                            Vin = "5F30414E-31E9-4804-B80C-26DC96CA19F8"
                        },
                        new
                        {
                            Id = 15,
                            Make = "Make 15",
                            Model = "Model 15",
                            Vin = "7A405D08-D58A-4CE2-ABFC-8405AC4A43E7"
                        },
                        new
                        {
                            Id = 16,
                            Make = "Make 16",
                            Model = "Model 16",
                            Vin = "D6DE5CB6-5E25-4A61-AC02-31DA9C871A05"
                        },
                        new
                        {
                            Id = 17,
                            Make = "Make 17",
                            Model = "Model 17",
                            Vin = "78CE82F3-6510-48FC-92AF-681831BD9F22"
                        },
                        new
                        {
                            Id = 18,
                            Make = "Make 18",
                            Model = "Model 18",
                            Vin = "9A97B23C-031D-41D3-9460-F20FF9CC0C91"
                        },
                        new
                        {
                            Id = 19,
                            Make = "Make 19",
                            Model = "Model 19",
                            Vin = "ABA38390-3CF6-4F0A-B23C-B6A5D907325B"
                        },
                        new
                        {
                            Id = 20,
                            Make = "Make 20",
                            Model = "Model 20",
                            Vin = "ADA7B432-9E77-4073-9DC6-DEBE0D971FC2"
                        },
                        new
                        {
                            Id = 21,
                            Make = "Make 21",
                            Model = "Model 21",
                            Vin = "73EFA40D-2E24-4644-83CB-2B44C217E50C"
                        },
                        new
                        {
                            Id = 22,
                            Make = "Make 22",
                            Model = "Model 22",
                            Vin = "D622B45A-AF3B-4B99-9118-E297E6B634D8"
                        },
                        new
                        {
                            Id = 23,
                            Make = "Make 23",
                            Model = "Model 23",
                            Vin = "CEFEE39F-6BA7-4D39-BA98-AD07094BBFE7"
                        },
                        new
                        {
                            Id = 24,
                            Make = "Make 24",
                            Model = "Model 24",
                            Vin = "BC317574-A9B0-49BB-AE7A-63001DD64ABD"
                        },
                        new
                        {
                            Id = 25,
                            Make = "Make 25",
                            Model = "Model 25",
                            Vin = "910E4206-C3BC-4915-B6B4-10CAA94C8207"
                        },
                        new
                        {
                            Id = 26,
                            Make = "Make 26",
                            Model = "Model 26",
                            Vin = "7A6866DF-13F3-4F4D-B619-66A910827906"
                        },
                        new
                        {
                            Id = 27,
                            Make = "Make 27",
                            Model = "Model 27",
                            Vin = "68F6E659-FC0D-454B-8662-89199DCD38B2"
                        },
                        new
                        {
                            Id = 28,
                            Make = "Make 28",
                            Model = "Model 28",
                            Vin = "3D79D1FC-1501-4BD7-AE4D-216E0BD60A60"
                        },
                        new
                        {
                            Id = 29,
                            Make = "Make 29",
                            Model = "Model 29",
                            Vin = "8BDB4263-8D0B-4C02-ADF3-F385030A4D8A"
                        },
                        new
                        {
                            Id = 30,
                            Make = "Make 30",
                            Model = "Model 30",
                            Vin = "D7DAC851-C5EA-4057-930A-D3138E4FD722"
                        },
                        new
                        {
                            Id = 31,
                            Make = "Make 31",
                            Model = "Model 31",
                            Vin = "51C213E0-49E4-405B-99D5-81F92F0F3EED"
                        },
                        new
                        {
                            Id = 32,
                            Make = "Make 32",
                            Model = "Model 32",
                            Vin = "1F154091-DED0-4E80-992C-7AAE477985BE"
                        },
                        new
                        {
                            Id = 33,
                            Make = "Make 33",
                            Model = "Model 33",
                            Vin = "E04F2BA8-A157-4775-BFDB-DB4F4F3B47EC"
                        },
                        new
                        {
                            Id = 34,
                            Make = "Make 34",
                            Model = "Model 34",
                            Vin = "A0DDB11C-666E-4E4A-9B7E-EBD8CA6F637D"
                        },
                        new
                        {
                            Id = 35,
                            Make = "Make 35",
                            Model = "Model 35",
                            Vin = "1194127D-E691-44F5-8096-9245C1339461"
                        },
                        new
                        {
                            Id = 36,
                            Make = "Make 36",
                            Model = "Model 36",
                            Vin = "2D0A9611-4321-4B4F-BB1C-32B5D789773C"
                        },
                        new
                        {
                            Id = 37,
                            Make = "Make 37",
                            Model = "Model 37",
                            Vin = "7032024C-97AB-409B-8FF6-2C1E468D63F7"
                        },
                        new
                        {
                            Id = 38,
                            Make = "Make 38",
                            Model = "Model 38",
                            Vin = "B674CB75-8B9A-476E-92D9-2045332B168C"
                        },
                        new
                        {
                            Id = 39,
                            Make = "Make 39",
                            Model = "Model 39",
                            Vin = "541D5644-9C78-49D5-BE41-0D64CD74E141"
                        },
                        new
                        {
                            Id = 40,
                            Make = "Make 40",
                            Model = "Model 40",
                            Vin = "C25FF597-007F-407E-8AB6-B242BCC330D3"
                        },
                        new
                        {
                            Id = 41,
                            Make = "Make 41",
                            Model = "Model 41",
                            Vin = "72B08361-912A-44AE-B2E6-6563A52A2778"
                        },
                        new
                        {
                            Id = 42,
                            Make = "Make 42",
                            Model = "Model 42",
                            Vin = "78106732-2911-4252-94FE-24B0CC22B7E7"
                        },
                        new
                        {
                            Id = 43,
                            Make = "Make 43",
                            Model = "Model 43",
                            Vin = "5E8158FF-FE02-4E61-BC78-A392A5A8ECCE"
                        },
                        new
                        {
                            Id = 44,
                            Make = "Make 44",
                            Model = "Model 44",
                            Vin = "BACAE821-9804-44C2-8D9B-70884DF8A310"
                        },
                        new
                        {
                            Id = 45,
                            Make = "Make 45",
                            Model = "Model 45",
                            Vin = "0310F749-8453-49FB-9AF0-2499194BF0B4"
                        },
                        new
                        {
                            Id = 46,
                            Make = "Make 46",
                            Model = "Model 46",
                            Vin = "36BF81C3-6E04-4B98-B9C1-1C98EA88CC4E"
                        },
                        new
                        {
                            Id = 47,
                            Make = "Make 47",
                            Model = "Model 47",
                            Vin = "4F091860-617B-41EB-9622-4146C9C5B3C0"
                        },
                        new
                        {
                            Id = 48,
                            Make = "Make 48",
                            Model = "Model 48",
                            Vin = "7CF1C25E-8217-485B-816B-16787719A5F9"
                        },
                        new
                        {
                            Id = 49,
                            Make = "Make 49",
                            Model = "Model 49",
                            Vin = "3356A89F-C26C-4477-A9CB-8A23CE66B924"
                        },
                        new
                        {
                            Id = 50,
                            Make = "Make 50",
                            Model = "Model 50",
                            Vin = "AF71B0ED-0CA8-4F48-A4B4-909259F9B933"
                        },
                        new
                        {
                            Id = 51,
                            Make = "Make 51",
                            Model = "Model 51",
                            Vin = "F6E6F376-451D-42CC-8315-BE7D1B4B088F"
                        },
                        new
                        {
                            Id = 52,
                            Make = "Make 52",
                            Model = "Model 52",
                            Vin = "70B98DE5-3476-469E-B49D-5883B6423B67"
                        },
                        new
                        {
                            Id = 53,
                            Make = "Make 53",
                            Model = "Model 53",
                            Vin = "0496E683-8EB6-4B17-AD02-51EB5D98DED1"
                        },
                        new
                        {
                            Id = 54,
                            Make = "Make 54",
                            Model = "Model 54",
                            Vin = "0ACC6E1B-4DF3-48E7-8C22-24B0EEFDCA8C"
                        },
                        new
                        {
                            Id = 55,
                            Make = "Make 55",
                            Model = "Model 55",
                            Vin = "02B5D061-841E-48D3-84DF-B689360F99A5"
                        },
                        new
                        {
                            Id = 56,
                            Make = "Make 56",
                            Model = "Model 56",
                            Vin = "FCC10ED5-1A56-44E6-BA08-2E917561B298"
                        },
                        new
                        {
                            Id = 57,
                            Make = "Make 57",
                            Model = "Model 57",
                            Vin = "F1020292-69B6-42D3-94F4-53B9C44CAE30"
                        },
                        new
                        {
                            Id = 58,
                            Make = "Make 58",
                            Model = "Model 58",
                            Vin = "2A909E1E-06CD-43EF-92E4-9A1DC8155959"
                        },
                        new
                        {
                            Id = 59,
                            Make = "Make 59",
                            Model = "Model 59",
                            Vin = "968FD5FA-B08E-4721-812D-88E1BD417137"
                        },
                        new
                        {
                            Id = 60,
                            Make = "Make 60",
                            Model = "Model 60",
                            Vin = "578BCF41-DDCA-4C97-B787-7C9842BE8DF5"
                        },
                        new
                        {
                            Id = 61,
                            Make = "Make 61",
                            Model = "Model 61",
                            Vin = "A00ACE7E-B28F-441D-A72E-CD09A8682437"
                        },
                        new
                        {
                            Id = 62,
                            Make = "Make 62",
                            Model = "Model 62",
                            Vin = "BD942F2C-5BE0-474A-AB33-0D007ABB2AE8"
                        },
                        new
                        {
                            Id = 63,
                            Make = "Make 63",
                            Model = "Model 63",
                            Vin = "14E71269-D02D-4FBD-A5C4-4430AABDA1E6"
                        },
                        new
                        {
                            Id = 64,
                            Make = "Make 64",
                            Model = "Model 64",
                            Vin = "3D5CBAFC-5265-4507-B27D-76222A915468"
                        },
                        new
                        {
                            Id = 65,
                            Make = "Make 65",
                            Model = "Model 65",
                            Vin = "5E626E7F-DB6B-4B47-B32F-0BB521F04DA8"
                        },
                        new
                        {
                            Id = 66,
                            Make = "Make 66",
                            Model = "Model 66",
                            Vin = "5E4F9E89-DCE2-472D-9F64-B704D721953B"
                        },
                        new
                        {
                            Id = 67,
                            Make = "Make 67",
                            Model = "Model 67",
                            Vin = "3699332D-85C2-462C-9335-90B4D9DA93FA"
                        },
                        new
                        {
                            Id = 68,
                            Make = "Make 68",
                            Model = "Model 68",
                            Vin = "2D12DA97-830D-47CC-AD8B-82C3BF2814E0"
                        },
                        new
                        {
                            Id = 69,
                            Make = "Make 69",
                            Model = "Model 69",
                            Vin = "D1852F21-17C4-45BE-A696-74A361D852EB"
                        },
                        new
                        {
                            Id = 70,
                            Make = "Make 70",
                            Model = "Model 70",
                            Vin = "368E9A15-AA8D-44C2-A387-DF72405B6839"
                        },
                        new
                        {
                            Id = 71,
                            Make = "Make 71",
                            Model = "Model 71",
                            Vin = "9D29C96F-F49F-44B6-B25B-CC89F7C8580C"
                        },
                        new
                        {
                            Id = 72,
                            Make = "Make 72",
                            Model = "Model 72",
                            Vin = "5C269FCC-CBBE-46D4-B6A3-9F6BEFAD1DED"
                        },
                        new
                        {
                            Id = 73,
                            Make = "Make 73",
                            Model = "Model 73",
                            Vin = "D404669A-0111-474D-A264-D8254B574BAB"
                        },
                        new
                        {
                            Id = 74,
                            Make = "Make 74",
                            Model = "Model 74",
                            Vin = "FC6625B8-49AB-40FB-BE27-038F6DF0C8CA"
                        },
                        new
                        {
                            Id = 75,
                            Make = "Make 75",
                            Model = "Model 75",
                            Vin = "79BC8544-B1C9-4310-A75A-569AAD6E8DC9"
                        },
                        new
                        {
                            Id = 76,
                            Make = "Make 76",
                            Model = "Model 76",
                            Vin = "61960486-7E43-40D9-8E6D-174F957E49B1"
                        },
                        new
                        {
                            Id = 77,
                            Make = "Make 77",
                            Model = "Model 77",
                            Vin = "617D3902-0088-4F40-A099-47BAF83FA3EE"
                        },
                        new
                        {
                            Id = 78,
                            Make = "Make 78",
                            Model = "Model 78",
                            Vin = "99058D51-A13B-42B0-997B-342F697CB9D7"
                        },
                        new
                        {
                            Id = 79,
                            Make = "Make 79",
                            Model = "Model 79",
                            Vin = "7D8962BB-D2B1-4ECE-A928-9765894EE7F9"
                        },
                        new
                        {
                            Id = 80,
                            Make = "Make 80",
                            Model = "Model 80",
                            Vin = "5F1B3A6C-D9F2-4D36-9038-2F5C4E703936"
                        },
                        new
                        {
                            Id = 81,
                            Make = "Make 81",
                            Model = "Model 81",
                            Vin = "6F9DCDC0-319A-42D7-B7CD-14F9B02ABA16"
                        },
                        new
                        {
                            Id = 82,
                            Make = "Make 82",
                            Model = "Model 82",
                            Vin = "BA2DC401-C7DB-4E89-B5F7-8E8FCF65317A"
                        },
                        new
                        {
                            Id = 83,
                            Make = "Make 83",
                            Model = "Model 83",
                            Vin = "990996EA-9D5E-41C8-A7E9-6F1E77FFF464"
                        },
                        new
                        {
                            Id = 84,
                            Make = "Make 84",
                            Model = "Model 84",
                            Vin = "847A808E-FA4E-435D-B713-39FD8D45ADB9"
                        },
                        new
                        {
                            Id = 85,
                            Make = "Make 85",
                            Model = "Model 85",
                            Vin = "FC4826D4-5249-4708-84EE-A4B905CE48D5"
                        },
                        new
                        {
                            Id = 86,
                            Make = "Make 86",
                            Model = "Model 86",
                            Vin = "9FE876DF-F32E-429F-8DD8-65DAE2BD59F4"
                        },
                        new
                        {
                            Id = 87,
                            Make = "Make 87",
                            Model = "Model 87",
                            Vin = "39D97616-68D8-44CC-B062-CCDD668332CA"
                        },
                        new
                        {
                            Id = 88,
                            Make = "Make 88",
                            Model = "Model 88",
                            Vin = "A40428ED-2718-43FD-91EC-E1063A4C4E48"
                        },
                        new
                        {
                            Id = 89,
                            Make = "Make 89",
                            Model = "Model 89",
                            Vin = "61B1F52F-AE08-4775-AF78-88C96213DDB7"
                        },
                        new
                        {
                            Id = 90,
                            Make = "Make 90",
                            Model = "Model 90",
                            Vin = "6B2F3225-0A18-48B8-9050-AFF54A57DBF9"
                        },
                        new
                        {
                            Id = 91,
                            Make = "Make 91",
                            Model = "Model 91",
                            Vin = "C80DA99A-1B0C-4913-9F92-4ADB157C10D7"
                        },
                        new
                        {
                            Id = 92,
                            Make = "Make 92",
                            Model = "Model 92",
                            Vin = "339E4A39-584D-4CEE-9A31-92A1B9E8C434"
                        },
                        new
                        {
                            Id = 93,
                            Make = "Make 93",
                            Model = "Model 93",
                            Vin = "436A62E8-0C6A-4EE4-A34A-157AC480FB2D"
                        },
                        new
                        {
                            Id = 94,
                            Make = "Make 94",
                            Model = "Model 94",
                            Vin = "D38C4BDC-BBD5-470F-A5D9-CBAD4E6FA8D3"
                        },
                        new
                        {
                            Id = 95,
                            Make = "Make 95",
                            Model = "Model 95",
                            Vin = "5D0A2791-6B7C-405D-B454-1105499E97BF"
                        },
                        new
                        {
                            Id = 96,
                            Make = "Make 96",
                            Model = "Model 96",
                            Vin = "4627838D-DA94-42BC-8DD1-CE6EA94C45E0"
                        },
                        new
                        {
                            Id = 97,
                            Make = "Make 97",
                            Model = "Model 97",
                            Vin = "A26FC50F-F53B-41E3-9C0A-1C7935AE2849"
                        },
                        new
                        {
                            Id = 98,
                            Make = "Make 98",
                            Model = "Model 98",
                            Vin = "C62BC6DB-5BB3-4E2B-8295-B2941BB3B265"
                        },
                        new
                        {
                            Id = 99,
                            Make = "Make 99",
                            Model = "Model 99",
                            Vin = "1D8E99BA-794F-4443-BE98-BFFBDFABD239"
                        },
                        new
                        {
                            Id = 100,
                            Make = "Make 100",
                            Model = "Model 100",
                            Vin = "363A78C1-6286-4B46-B142-7502A6B8D446"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
