// <auto-generated />
using System;
using CarListingApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarListingApp.API.Migrations
{
    [DbContext(typeof(CarListDBContext))]
    partial class CarListDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("CarListingApp.API.Data.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Make = "Make 1",
                            Model = "Model 1",
                            Vin = "E5C30D90-162F-4F87-B9D7-2D2DACBE3D15"
                        },
                        new
                        {
                            Id = 2,
                            Make = "Make 2",
                            Model = "Model 2",
                            Vin = "897614D7-FD9E-480C-B153-F375A6046773"
                        },
                        new
                        {
                            Id = 3,
                            Make = "Make 3",
                            Model = "Model 3",
                            Vin = "8DF1424C-6C4F-4893-8C31-343BF7C06162"
                        },
                        new
                        {
                            Id = 4,
                            Make = "Make 4",
                            Model = "Model 4",
                            Vin = "10E83C15-6B5B-4DB0-9261-5065DCDF97C2"
                        },
                        new
                        {
                            Id = 5,
                            Make = "Make 5",
                            Model = "Model 5",
                            Vin = "6CDC04A2-AB95-4008-91C8-28645774F2A2"
                        },
                        new
                        {
                            Id = 6,
                            Make = "Make 6",
                            Model = "Model 6",
                            Vin = "E528FABA-3086-4386-AC2D-D01CF2D77575"
                        },
                        new
                        {
                            Id = 7,
                            Make = "Make 7",
                            Model = "Model 7",
                            Vin = "7015C55C-3BB6-482B-95A9-F045DA03BDA7"
                        },
                        new
                        {
                            Id = 8,
                            Make = "Make 8",
                            Model = "Model 8",
                            Vin = "6F860AAE-53FD-415B-9D3D-F54004B91764"
                        },
                        new
                        {
                            Id = 9,
                            Make = "Make 9",
                            Model = "Model 9",
                            Vin = "30E37ACC-BAEC-47FD-AD82-1B293B86D2A1"
                        },
                        new
                        {
                            Id = 10,
                            Make = "Make 10",
                            Model = "Model 10",
                            Vin = "9A7C59BD-227B-4376-BEA1-7F51510AEDB4"
                        },
                        new
                        {
                            Id = 11,
                            Make = "Make 11",
                            Model = "Model 11",
                            Vin = "2B61AFA6-1696-46E2-8F1F-F065D7CD01B0"
                        },
                        new
                        {
                            Id = 12,
                            Make = "Make 12",
                            Model = "Model 12",
                            Vin = "A72859A5-9124-4275-82A3-71A15DBB5EB9"
                        },
                        new
                        {
                            Id = 13,
                            Make = "Make 13",
                            Model = "Model 13",
                            Vin = "66FD9E0B-B305-422A-AF57-F3843E111DF5"
                        },
                        new
                        {
                            Id = 14,
                            Make = "Make 14",
                            Model = "Model 14",
                            Vin = "C91AC291-B8DD-4AA9-87FB-AFEE8AAFDA5A"
                        },
                        new
                        {
                            Id = 15,
                            Make = "Make 15",
                            Model = "Model 15",
                            Vin = "8D81AB6F-6692-4E7C-83E7-A2B64B5CFF9B"
                        },
                        new
                        {
                            Id = 16,
                            Make = "Make 16",
                            Model = "Model 16",
                            Vin = "B44877A8-ED35-4095-A178-2915C16D4B7E"
                        },
                        new
                        {
                            Id = 17,
                            Make = "Make 17",
                            Model = "Model 17",
                            Vin = "2C098D9D-1541-400D-89F1-C98B14295C0C"
                        },
                        new
                        {
                            Id = 18,
                            Make = "Make 18",
                            Model = "Model 18",
                            Vin = "190050AD-1FF4-4874-B0EB-6DD2914E1078"
                        },
                        new
                        {
                            Id = 19,
                            Make = "Make 19",
                            Model = "Model 19",
                            Vin = "7C5399B8-1924-4BFC-82F0-6476A85A8222"
                        },
                        new
                        {
                            Id = 20,
                            Make = "Make 20",
                            Model = "Model 20",
                            Vin = "607CCB0E-84EC-4AC4-9A6B-E2B97193291D"
                        },
                        new
                        {
                            Id = 21,
                            Make = "Make 21",
                            Model = "Model 21",
                            Vin = "26F8498F-881E-41AC-93E3-D545747C1631"
                        },
                        new
                        {
                            Id = 22,
                            Make = "Make 22",
                            Model = "Model 22",
                            Vin = "5AA8794C-AF02-48A9-9D3A-0F41A1303443"
                        },
                        new
                        {
                            Id = 23,
                            Make = "Make 23",
                            Model = "Model 23",
                            Vin = "47854390-6CB6-4D51-B34D-158483061AD4"
                        },
                        new
                        {
                            Id = 24,
                            Make = "Make 24",
                            Model = "Model 24",
                            Vin = "FB984363-7CAA-4E18-ABF2-3D2133403984"
                        },
                        new
                        {
                            Id = 25,
                            Make = "Make 25",
                            Model = "Model 25",
                            Vin = "2DF867C6-D2A4-4403-A9BE-7A7B8F53E07C"
                        },
                        new
                        {
                            Id = 26,
                            Make = "Make 26",
                            Model = "Model 26",
                            Vin = "1DAAEDEC-1D82-4AC0-8AD8-3C45C92DA0F1"
                        },
                        new
                        {
                            Id = 27,
                            Make = "Make 27",
                            Model = "Model 27",
                            Vin = "61AE3323-F225-4658-A21B-4D44EBF01B0F"
                        },
                        new
                        {
                            Id = 28,
                            Make = "Make 28",
                            Model = "Model 28",
                            Vin = "FDD1A8F4-CB54-4B7E-BE08-852D8F4A5BDA"
                        },
                        new
                        {
                            Id = 29,
                            Make = "Make 29",
                            Model = "Model 29",
                            Vin = "F3C6894A-8529-4BAE-9351-3A61BDE7F420"
                        },
                        new
                        {
                            Id = 30,
                            Make = "Make 30",
                            Model = "Model 30",
                            Vin = "E756A680-CE67-408C-A70B-04A033F5AEC5"
                        },
                        new
                        {
                            Id = 31,
                            Make = "Make 31",
                            Model = "Model 31",
                            Vin = "2F919450-51C0-4677-8792-E9B15AA9D55F"
                        },
                        new
                        {
                            Id = 32,
                            Make = "Make 32",
                            Model = "Model 32",
                            Vin = "A2C4AD18-FB47-499B-9D19-6FD03F5718EF"
                        },
                        new
                        {
                            Id = 33,
                            Make = "Make 33",
                            Model = "Model 33",
                            Vin = "E5B90E84-22A6-45E8-AA31-8EF736E967AD"
                        },
                        new
                        {
                            Id = 34,
                            Make = "Make 34",
                            Model = "Model 34",
                            Vin = "5ED4253F-BB18-41AF-A9BF-E3033847D6BB"
                        },
                        new
                        {
                            Id = 35,
                            Make = "Make 35",
                            Model = "Model 35",
                            Vin = "568DA3E1-B7A2-436D-AEE5-9B5024E08479"
                        },
                        new
                        {
                            Id = 36,
                            Make = "Make 36",
                            Model = "Model 36",
                            Vin = "BBCC76AC-0591-4115-8ABC-490912FF9A15"
                        },
                        new
                        {
                            Id = 37,
                            Make = "Make 37",
                            Model = "Model 37",
                            Vin = "BF3BA832-FEF3-4280-A48F-FD3671CDA7DE"
                        },
                        new
                        {
                            Id = 38,
                            Make = "Make 38",
                            Model = "Model 38",
                            Vin = "6D0B077B-F692-44E1-9963-F53BEB4EAC2D"
                        },
                        new
                        {
                            Id = 39,
                            Make = "Make 39",
                            Model = "Model 39",
                            Vin = "F73D43B6-2F2A-4906-838B-C89D7D32A98D"
                        },
                        new
                        {
                            Id = 40,
                            Make = "Make 40",
                            Model = "Model 40",
                            Vin = "7F4F3095-4AB2-46F2-8198-B193970EA138"
                        },
                        new
                        {
                            Id = 41,
                            Make = "Make 41",
                            Model = "Model 41",
                            Vin = "F5CC5DE6-1087-4724-9ECE-6D2401415D9C"
                        },
                        new
                        {
                            Id = 42,
                            Make = "Make 42",
                            Model = "Model 42",
                            Vin = "A0741EE5-D19A-492E-8502-02B1DC0BDDA2"
                        },
                        new
                        {
                            Id = 43,
                            Make = "Make 43",
                            Model = "Model 43",
                            Vin = "CC224B6E-BC60-455E-939C-A889C1117CAF"
                        },
                        new
                        {
                            Id = 44,
                            Make = "Make 44",
                            Model = "Model 44",
                            Vin = "B4DA6469-38A5-4E4E-81EF-714F901A8A23"
                        },
                        new
                        {
                            Id = 45,
                            Make = "Make 45",
                            Model = "Model 45",
                            Vin = "482A1D08-EA13-48E4-9089-7CC2304A6203"
                        },
                        new
                        {
                            Id = 46,
                            Make = "Make 46",
                            Model = "Model 46",
                            Vin = "D84CB03D-9E13-4159-BA55-4ECF7D0B71B3"
                        },
                        new
                        {
                            Id = 47,
                            Make = "Make 47",
                            Model = "Model 47",
                            Vin = "2E57BCEE-C916-4C33-AB34-C17F1E8E3D06"
                        },
                        new
                        {
                            Id = 48,
                            Make = "Make 48",
                            Model = "Model 48",
                            Vin = "63F3672A-C76E-414C-A9B7-D412DC5C385F"
                        },
                        new
                        {
                            Id = 49,
                            Make = "Make 49",
                            Model = "Model 49",
                            Vin = "80DEFA4A-075E-4E67-B20A-340D293192AF"
                        },
                        new
                        {
                            Id = 50,
                            Make = "Make 50",
                            Model = "Model 50",
                            Vin = "39831621-9D7B-401D-83C1-AA152D20F416"
                        },
                        new
                        {
                            Id = 51,
                            Make = "Make 51",
                            Model = "Model 51",
                            Vin = "A37CF695-1DB4-4F61-A44B-8286B9AE66DE"
                        },
                        new
                        {
                            Id = 52,
                            Make = "Make 52",
                            Model = "Model 52",
                            Vin = "AF167A7D-9C77-4CFB-8A59-B684F4765FA6"
                        },
                        new
                        {
                            Id = 53,
                            Make = "Make 53",
                            Model = "Model 53",
                            Vin = "29E6DD31-F606-4811-AA0A-D5871ECC8202"
                        },
                        new
                        {
                            Id = 54,
                            Make = "Make 54",
                            Model = "Model 54",
                            Vin = "D57A56D1-434A-4C11-BCBB-E50B0AFB41FC"
                        },
                        new
                        {
                            Id = 55,
                            Make = "Make 55",
                            Model = "Model 55",
                            Vin = "01F4EB29-076C-498F-A69D-9E25A849C6AB"
                        },
                        new
                        {
                            Id = 56,
                            Make = "Make 56",
                            Model = "Model 56",
                            Vin = "16B9B5D2-D5E6-4A81-AEB5-6560F79C41F5"
                        },
                        new
                        {
                            Id = 57,
                            Make = "Make 57",
                            Model = "Model 57",
                            Vin = "5E359962-8733-4C3D-8313-74FECC60668D"
                        },
                        new
                        {
                            Id = 58,
                            Make = "Make 58",
                            Model = "Model 58",
                            Vin = "C7142B5D-1BA3-4389-91A0-C8A15E192428"
                        },
                        new
                        {
                            Id = 59,
                            Make = "Make 59",
                            Model = "Model 59",
                            Vin = "F9F8E937-4F4F-4061-B59B-6E73ABE7017B"
                        },
                        new
                        {
                            Id = 60,
                            Make = "Make 60",
                            Model = "Model 60",
                            Vin = "445B967E-5F7C-42C6-9075-02BB98752FBD"
                        },
                        new
                        {
                            Id = 61,
                            Make = "Make 61",
                            Model = "Model 61",
                            Vin = "89060E81-9E38-4F43-9508-64487A33DE8C"
                        },
                        new
                        {
                            Id = 62,
                            Make = "Make 62",
                            Model = "Model 62",
                            Vin = "FD0EB26E-BAA8-4095-816C-2171F1ACA438"
                        },
                        new
                        {
                            Id = 63,
                            Make = "Make 63",
                            Model = "Model 63",
                            Vin = "AF76FD9E-07E1-4AB8-9AB9-2CE1FBD86973"
                        },
                        new
                        {
                            Id = 64,
                            Make = "Make 64",
                            Model = "Model 64",
                            Vin = "56FB164A-D9F5-4A94-A2C0-ABA65EEC4F0C"
                        },
                        new
                        {
                            Id = 65,
                            Make = "Make 65",
                            Model = "Model 65",
                            Vin = "C3B17B0C-97F6-4C5F-9B3D-120E95B4A8EF"
                        },
                        new
                        {
                            Id = 66,
                            Make = "Make 66",
                            Model = "Model 66",
                            Vin = "BDA655B7-A760-4158-B61D-7AF10D2A4469"
                        },
                        new
                        {
                            Id = 67,
                            Make = "Make 67",
                            Model = "Model 67",
                            Vin = "BFECF2BD-1304-4778-80B7-884CF6A7CDAB"
                        },
                        new
                        {
                            Id = 68,
                            Make = "Make 68",
                            Model = "Model 68",
                            Vin = "E5948F40-932B-4D13-9989-22BEC448E37C"
                        },
                        new
                        {
                            Id = 69,
                            Make = "Make 69",
                            Model = "Model 69",
                            Vin = "E89A58C6-FB18-4C33-A2A2-CB64B972C87A"
                        },
                        new
                        {
                            Id = 70,
                            Make = "Make 70",
                            Model = "Model 70",
                            Vin = "C28750B7-4ECB-4252-A0DD-5156DBFB218E"
                        },
                        new
                        {
                            Id = 71,
                            Make = "Make 71",
                            Model = "Model 71",
                            Vin = "6FF24285-3A28-4F13-BF37-400D0FE27721"
                        },
                        new
                        {
                            Id = 72,
                            Make = "Make 72",
                            Model = "Model 72",
                            Vin = "6DC413A7-D29E-45A4-9504-C941D85980DC"
                        },
                        new
                        {
                            Id = 73,
                            Make = "Make 73",
                            Model = "Model 73",
                            Vin = "42843406-8811-4743-8C98-8F7A23502616"
                        },
                        new
                        {
                            Id = 74,
                            Make = "Make 74",
                            Model = "Model 74",
                            Vin = "E8E98B60-65FF-4C23-BA52-9D69C1924213"
                        },
                        new
                        {
                            Id = 75,
                            Make = "Make 75",
                            Model = "Model 75",
                            Vin = "56D3515D-C381-4313-B6B5-5769C78C921F"
                        },
                        new
                        {
                            Id = 76,
                            Make = "Make 76",
                            Model = "Model 76",
                            Vin = "1CF10343-AD73-4C64-8940-B9C98DAC1D28"
                        },
                        new
                        {
                            Id = 77,
                            Make = "Make 77",
                            Model = "Model 77",
                            Vin = "B7AAD306-72A4-4493-90A9-AE41DCFB7F4E"
                        },
                        new
                        {
                            Id = 78,
                            Make = "Make 78",
                            Model = "Model 78",
                            Vin = "B798EB76-2E05-4E47-A8C0-77E592074143"
                        },
                        new
                        {
                            Id = 79,
                            Make = "Make 79",
                            Model = "Model 79",
                            Vin = "68696E37-E81F-4C1C-AC1F-C218A8FDEBAE"
                        },
                        new
                        {
                            Id = 80,
                            Make = "Make 80",
                            Model = "Model 80",
                            Vin = "606EF72C-B256-49C1-8E0B-A2C691A234B3"
                        },
                        new
                        {
                            Id = 81,
                            Make = "Make 81",
                            Model = "Model 81",
                            Vin = "25DF56CA-282A-4301-86BA-156603E21399"
                        },
                        new
                        {
                            Id = 82,
                            Make = "Make 82",
                            Model = "Model 82",
                            Vin = "CE794AC9-07F1-4D1D-B047-BDB97E4D845F"
                        },
                        new
                        {
                            Id = 83,
                            Make = "Make 83",
                            Model = "Model 83",
                            Vin = "BC797A3B-43FB-42F8-8BD4-1CCC775620AF"
                        },
                        new
                        {
                            Id = 84,
                            Make = "Make 84",
                            Model = "Model 84",
                            Vin = "F1BFAD43-B2B7-442A-B0D4-DA28BDFEA39D"
                        },
                        new
                        {
                            Id = 85,
                            Make = "Make 85",
                            Model = "Model 85",
                            Vin = "345F33D6-45C8-445C-BBF0-9B7491E6BF02"
                        },
                        new
                        {
                            Id = 86,
                            Make = "Make 86",
                            Model = "Model 86",
                            Vin = "9B0B00C6-B231-42D5-BEFA-FA5B6672F9E1"
                        },
                        new
                        {
                            Id = 87,
                            Make = "Make 87",
                            Model = "Model 87",
                            Vin = "2F29A7F3-87D4-4343-8FF0-F308E782C333"
                        },
                        new
                        {
                            Id = 88,
                            Make = "Make 88",
                            Model = "Model 88",
                            Vin = "76F72F62-F19A-463B-B1A1-1A8F818DD83C"
                        },
                        new
                        {
                            Id = 89,
                            Make = "Make 89",
                            Model = "Model 89",
                            Vin = "24BCAB44-65E0-481E-9BBB-6F3906374898"
                        },
                        new
                        {
                            Id = 90,
                            Make = "Make 90",
                            Model = "Model 90",
                            Vin = "2C21A898-21DC-4928-A786-944ED17C1827"
                        },
                        new
                        {
                            Id = 91,
                            Make = "Make 91",
                            Model = "Model 91",
                            Vin = "EBED270F-8164-4200-9431-332C17241728"
                        },
                        new
                        {
                            Id = 92,
                            Make = "Make 92",
                            Model = "Model 92",
                            Vin = "B704C8F6-A4A3-44B0-B274-54CA1DF67CB8"
                        },
                        new
                        {
                            Id = 93,
                            Make = "Make 93",
                            Model = "Model 93",
                            Vin = "CEBE61FA-285A-490A-8D81-72D7F960B368"
                        },
                        new
                        {
                            Id = 94,
                            Make = "Make 94",
                            Model = "Model 94",
                            Vin = "0A6D3BE9-3673-4E7A-9A56-EFA9ADFF5FE8"
                        },
                        new
                        {
                            Id = 95,
                            Make = "Make 95",
                            Model = "Model 95",
                            Vin = "4343BC1F-391B-4A4E-9DAF-405A6F34C375"
                        },
                        new
                        {
                            Id = 96,
                            Make = "Make 96",
                            Model = "Model 96",
                            Vin = "10460E42-8B1C-48E6-86AC-BA18BEE1584E"
                        },
                        new
                        {
                            Id = 97,
                            Make = "Make 97",
                            Model = "Model 97",
                            Vin = "FE2C7AB9-9354-49D9-A0F9-B0A5B3F0A76D"
                        },
                        new
                        {
                            Id = 98,
                            Make = "Make 98",
                            Model = "Model 98",
                            Vin = "46589AB6-E4AA-4B0B-B0D3-C6D46D543899"
                        },
                        new
                        {
                            Id = 99,
                            Make = "Make 99",
                            Model = "Model 99",
                            Vin = "E18FE7A8-6FD9-4228-A1A2-059A26A89C26"
                        },
                        new
                        {
                            Id = 100,
                            Make = "Make 100",
                            Model = "Model 100",
                            Vin = "CF295F9D-B982-41E7-B57A-98F6E140B470"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c82225b5-020c-48de-beef-c2fc0b14b62f",
                            ConcurrencyStamp = "0ebf9642-4ad4-4d5d-8c01-762a23f979aa",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "55aa28a3-b506-45a9-aac1-e3093a894f5c",
                            ConcurrencyStamp = "c00e884f-15d2-4eca-8a20-390badf1857c",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "06bde6ec-53ef-4899-8f70-448dfde1061d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "079b40a5-2387-4d2d-ab25-5b13bd98708a",
                            Email = "administrator@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMINISTRATOR@LOCALHOST.COM",
                            NormalizedUserName = "ADMINISTRATOR@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELyZexhRRSKjyvCKLeuWTQ/mZQY7JbvwKtstikuDevJLMUieNjm54XL4doiYCgmtnQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "88b35dfb-7b49-4bf9-b02a-69473bc09a00",
                            TwoFactorEnabled = false,
                            UserName = "administrator@localhost.com"
                        },
                        new
                        {
                            Id = "f3f82840-4505-403e-9679-db20a2f9db8b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "00a97e9c-f7e0-49c3-b17b-455470228ce2",
                            Email = "user@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@LOCALHOST.COM",
                            NormalizedUserName = "USER@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFba92FyurbS1ODhX9CuWfdnT30e9L0R8Y93UarUY3KdKC0bTLNClAAZ7t6YR63rpw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "880288fe-0358-4ed8-93d4-a49e41a9f415",
                            TwoFactorEnabled = false,
                            UserName = "user@localhost.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "06bde6ec-53ef-4899-8f70-448dfde1061d",
                            RoleId = "c82225b5-020c-48de-beef-c2fc0b14b62f"
                        },
                        new
                        {
                            UserId = "f3f82840-4505-403e-9679-db20a2f9db8b",
                            RoleId = "55aa28a3-b506-45a9-aac1-e3093a894f5c"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
